# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Eclipse Tycho build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '21'
       cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.9   
    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Start Xvfb
      run: |
        Xvfb :99 &
        export DISPLAY=:99
        sleep 3
        mvn clean verify -ntp
